# Generated by Django 5.2.16 on 2026-07-12 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CSR Activity', 'CSR Activity'), ('Challenge', 'Challenge')], max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('employee_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('esg_manager', 'ESG Manager'), ('dept_head', 'Department Head'), ('employee', 'Employee')], default='employee', max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='core.employee'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_emission_calculation_enabled', models.BooleanField(default=True)),
                ('evidence_requirement_enabled', models.BooleanField(default=True)),
                ('badge_auto_award_enabled', models.BooleanField(default=True)),
                ('environmental_weight', models.DecimalField(decimal_places=4, default=0.4, max_digits=5)),
                ('social_weight', models.DecimalField(decimal_places=4, default=0.3, max_digits=5)),
                ('governance_weight', models.DecimalField(decimal_places=4, default=0.3, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('environmental_weight', models.F('environmental_weight'))), name='dummy_constraint_for_schema')],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('xp_total__gte', 0)), name='xp_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('points_balance__gte', 0)), name='points_must_be_positive'),
        ),
    ]
