# Generated by Django 5.2.16 on 2026-07-12 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ESG Policies',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('audit_type', models.CharField(max_length=100)),
                ('audit_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=50)),
                ('findings', models.TextField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_audits', to='core.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('overdue', 'Overdue'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_issues', to='governance.audit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_issues', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='core.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='governance.esgpolicy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('policy', 'employee'), name='unique_policy_employee_acknowledgement')],
            },
        ),
    ]
