# Generated by Django 5.2.16 on 2026-07-12 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environmental_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('social_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('governance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.department')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['department', 'period_start', 'period_end'], name='idx_dept_score_period')],
                'constraints': [models.CheckConstraint(condition=models.Q(('environmental_score__range', (0, 100))), name='env_score_range'), models.CheckConstraint(condition=models.Q(('social_score__range', (0, 100))), name='social_score_range'), models.CheckConstraint(condition=models.Q(('governance_score__range', (0, 100))), name='gov_score_range'), models.CheckConstraint(condition=models.Q(('total_score__range', (0, 100))), name='total_score_range')],
            },
        ),
    ]
