# Generated by Django 5.2.16 on 2026-07-12 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=100)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('standard_reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_goals', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('co2e_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source_record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_record_id', models.UUIDField(blank=True, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_transactions', to='core.department')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_transactions', to='environmental.emissionfactor')),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'transaction_date'], name='idx_carbon_tx_dept_date')],
            },
        ),
        migrations.CreateModel(
            name='ProductESGProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carbon_footprint_co2e', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('recycled_content_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('has_biodegradable_packaging', models.BooleanField(default=False)),
                ('hazardous_materials_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esg_profile', to='environmental.product')),
            ],
            options={
                'verbose_name_plural': 'Product ESG Profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('carbon_footprint_co2e__gte', 0)), name='carbon_footprint_non_negative'), models.CheckConstraint(condition=models.Q(('recycled_content_pct__range', (0, 100))), name='recycled_content_range')],
            },
        ),
    ]
