# Generated by Django 5.2.16 on 2026-07-12 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_model', models.CharField(max_length=100)),
                ('source_field', models.CharField(max_length=100)),
                ('computation', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(max_length=50)),
                ('periodicity', models.CharField(max_length=50)),
                ('assignment_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_required', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='core.category')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=50)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='gamification.challenge')),
                ('goal_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='gamification.goaldefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unlock_rule_type', models.CharField(max_length=100)),
                ('unlock_threshold', models.DecimalField(decimal_places=4, max_digits=12)),
                ('grant_permission', models.CharField(blank=True, max_length=100, null=True)),
                ('limitation_number', models.IntegerField(blank=True, null=True)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
                ('unlock_goal_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='gamification.goaldefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('point_cost', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='reward_stock_must_be_positive'), models.CheckConstraint(condition=models.Q(('point_cost__gte', 0)), name='reward_cost_must_be_positive')],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('points_spent', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.employee')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='gamification.reward')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('proof_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_challenges', to='core.employee')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='gamification.challenge')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='core.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('challenge', 'employee'), name='unique_challenge_employee_participation')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('award_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=50)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_badges', to='gamification.badge')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_badges', to='core.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'badge'), name='unique_employee_badge')],
            },
        ),
    ]
